class BibleBookInfo {
  final int id;
  final String name;
  final int chapterCount;
  final bool isOldTestament;

  BibleBookInfo({required this.id, required this.name, required this.chapterCount, required this.isOldTestament});
}

final List<BibleBookInfo> allBibleBooks = [
  // 구약 39권
  BibleBookInfo(id: 1, name: "창세기", chapterCount: 50, isOldTestament: true),
  BibleBookInfo(id: 2, name: "출애굽기", chapterCount: 40, isOldTestament: true),
  BibleBookInfo(id: 3, name: "레위기", chapterCount: 27, isOldTestament: true),
  BibleBookInfo(id: 4, name: "민수기", chapterCount: 36, isOldTestament: true),
  BibleBookInfo(id: 5, name: "신명기", chapterCount: 34, isOldTestament: true),
  BibleBookInfo(id: 6, name: "여호수아", chapterCount: 24, isOldTestament: true),
  BibleBookInfo(id: 7, name: "사사기", chapterCount: 21, isOldTestament: true),
  BibleBookInfo(id: 8, name: "룻기", chapterCount: 4, isOldTestament: true),
  BibleBookInfo(id: 9, name: "사무엘상", chapterCount: 31, isOldTestament: true),
  BibleBookInfo(id: 10, name: "사무엘하", chapterCount: 24, isOldTestament: true),
  BibleBookInfo(id: 11, name: "열왕기상", chapterCount: 22, isOldTestament: true),
  BibleBookInfo(id: 12, name: "열왕기하", chapterCount: 25, isOldTestament: true),
  BibleBookInfo(id: 13, name: "역대상", chapterCount: 29, isOldTestament: true),
  BibleBookInfo(id: 14, name: "역대하", chapterCount: 36, isOldTestament: true),
  BibleBookInfo(id: 15, name: "에스라", chapterCount: 10, isOldTestament: true),
  BibleBookInfo(id: 16, name: "느헤미야", chapterCount: 13, isOldTestament: true),
  BibleBookInfo(id: 17, name: "에스더", chapterCount: 10, isOldTestament: true),
  BibleBookInfo(id: 18, name: "욥기", chapterCount: 42, isOldTestament: true),
  BibleBookInfo(id: 19, name: "시편", chapterCount: 150, isOldTestament: true),
  BibleBookInfo(id: 20, name: "잠언", chapterCount: 31, isOldTestament: true),
  BibleBookInfo(id: 21, name: "전도서", chapterCount: 12, isOldTestament: true),
  BibleBookInfo(id: 22, name: "아가", chapterCount: 8, isOldTestament: true),
  BibleBookInfo(id: 23, name: "이사야", chapterCount: 66, isOldTestament: true),
  BibleBookInfo(id: 24, name: "예레미야", chapterCount: 52, isOldTestament: true),
  BibleBookInfo(id: 25, name: "예레미야 애가", chapterCount: 5, isOldTestament: true),
  BibleBookInfo(id: 26, name: "에스겔", chapterCount: 48, isOldTestament: true),
  BibleBookInfo(id: 27, name: "다니엘", chapterCount: 12, isOldTestament: true),
  BibleBookInfo(id: 28, name: "호세아", chapterCount: 14, isOldTestament: true),
  BibleBookInfo(id: 29, name: "요엘", chapterCount: 3, isOldTestament: true),
  BibleBookInfo(id: 30, name: "아모스", chapterCount: 9, isOldTestament: true),
  BibleBookInfo(id: 31, name: "오바댜", chapterCount: 1, isOldTestament: true),
  BibleBookInfo(id: 32, name: "요나", chapterCount: 4, isOldTestament: true),
  BibleBookInfo(id: 33, name: "미가", chapterCount: 7, isOldTestament: true),
  BibleBookInfo(id: 34, name: "나훔", chapterCount: 3, isOldTestament: true),
  BibleBookInfo(id: 35, name: "하박국", chapterCount: 3, isOldTestament: true),
  BibleBookInfo(id: 36, name: "스바냐", chapterCount: 3, isOldTestament: true),
  BibleBookInfo(id: 37, name: "학개", chapterCount: 2, isOldTestament: true),
  BibleBookInfo(id: 38, name: "스가랴", chapterCount: 14, isOldTestament: true),
  BibleBookInfo(id: 39, name: "말라기", chapterCount: 4, isOldTestament: true),
  
  // 신약 27권
  BibleBookInfo(id: 40, name: "마태복음", chapterCount: 28, isOldTestament: false),
  BibleBookInfo(id: 41, name: "마가복음", chapterCount: 16, isOldTestament: false),
  BibleBookInfo(id: 42, name: "누가복음", chapterCount: 24, isOldTestament: false),
  BibleBookInfo(id: 43, name: "요한복음", chapterCount: 21, isOldTestament: false),
  BibleBookInfo(id: 44, name: "사도행전", chapterCount: 28, isOldTestament: false),
  BibleBookInfo(id: 45, name: "로마서", chapterCount: 16, isOldTestament: false),
  BibleBookInfo(id: 46, name: "고린도전서", chapterCount: 16, isOldTestament: false),
  BibleBookInfo(id: 47, name: "고린도후서", chapterCount: 13, isOldTestament: false),
  BibleBookInfo(id: 48, name: "갈라디아서", chapterCount: 6, isOldTestament: false),
  BibleBookInfo(id: 49, name: "에베소서", chapterCount: 6, isOldTestament: false),
  BibleBookInfo(id: 50, name: "빌립보서", chapterCount: 4, isOldTestament: false),
  BibleBookInfo(id: 51, name: "골로새서", chapterCount: 4, isOldTestament: false),
  BibleBookInfo(id: 52, name: "데살로니가전서", chapterCount: 5, isOldTestament: false),
  BibleBookInfo(id: 53, name: "데살로니가후서", chapterCount: 3, isOldTestament: false),
  BibleBookInfo(id: 54, name: "디모데전서", chapterCount: 6, isOldTestament: false),
  BibleBookInfo(id: 55, name: "디모데후서", chapterCount: 4, isOldTestament: false),
  BibleBookInfo(id: 56, name: "디도서", chapterCount: 3, isOldTestament: false),
  BibleBookInfo(id: 57, name: "빌레몬서", chapterCount: 1, isOldTestament: false),
  BibleBookInfo(id: 58, name: "히브리서", chapterCount: 13, isOldTestament: false),
  BibleBookInfo(id: 59, name: "야고보서", chapterCount: 5, isOldTestament: false),
  BibleBookInfo(id: 60, name: "베드로전서", chapterCount: 5, isOldTestament: false),
  BibleBookInfo(id: 61, name: "베드로후서", chapterCount: 3, isOldTestament: false),
  BibleBookInfo(id: 62, name: "요한일서", chapterCount: 5, isOldTestament: false),
  BibleBookInfo(id: 63, name: "요한이서", chapterCount: 1, isOldTestament: false),
  BibleBookInfo(id: 64, name: "요한삼서", chapterCount: 1, isOldTestament: false),
  BibleBookInfo(id: 65, name: "유다서", chapterCount: 1, isOldTestament: false),
  BibleBookInfo(id: 66, name: "요한계시록", chapterCount: 22, isOldTestament: false),
];
