package com.veritasbible.app.util

object LanguageManager {
    fun getTranslation(key: String, language: String): String {
        val en = mapOf(
            // Tabs
            "tab_reader" to "Bible",
            "tab_search" to "Search",
            "tab_study" to "Study",
            "tab_dashboard" to "Analytics",
            "tab_notes" to "Study Notes",
            "tab_settings" to "Settings",
            
            // Reader screen
            "reader_title" to "Veritas Bible Study",
            "reader_font_size" to "Font Size",
            "reader_screen_theme" to "Reader Accent",
            "reader_timer_study" to "Daily Active Study: ",
            "reader_chapter" to "Ch",
            "reader_verse" to "v",
            "no_scripture_title" to "Scripture data not loaded",
            "no_scripture_desc" to "Please download and install the offline Bible resource packet on your device.",
            "download_bible_btn" to "Download Bible Data",
            "reading_index_loading" to "Loading index database...",
            
            // Search screen
            "search_title" to "Deep Corpus Search",
            "search_placeholder" to "Search keyword (e.g., God, Jesus)...",
            "search_no_results" to "No search results match the query.",
            "search_min_chars" to "Enter at least 2 characters to start search",
            "search_total_results" to "found %d instances in text.",
            
            // Dashboard
            "dashboard_title" to "Analytics Dashboard",
            "db_weekly_summary" to "Weekly Reading Sessions Log",
            "db_cumulative_stats" to "Cumulative Statistics",
            "db_total_chapters" to "Total Read Chapters",
            "db_total_seconds" to "Total Session Time",
            "db_goal_status" to "Daily Target Goal status",
            "db_percentage_complete" to "Percentage Completed",
            "db_goal_target" to "Active Target Goal",
            "db_update_goal" to "Adjust Active Target",
            "db_new_entry" to "Add Manual Reading Entry",
            "db_book_label" to "Book Name",
            "db_chap_label" to "Chapter",
            "db_add_btn" to "Save Study Entry",
            "db_goal_suffix" to " Chapters",
            "db_seconds_suffix" to " min",
            
            // Notes
            "notes_title" to "Encrypted Study Notes",
            "notes_add_placeholder" to "Write your thoughts on %s %d:%d...",
            "notes_save_btn" to "Secure Note",
            "notes_empty_state" to "No study notes matching current filters.",
            "notes_tag_field" to "Topic Tag (Optional)",
            
            // Settings
            "settings_title" to "Settings & Backups",
            "settings_theme_section" to "System Visual Environment Theme",
            "theme_system" to "System Config",
            "theme_light" to "Light Mode",
            "theme_dark" to "Dark Mode",
            "settings_data_section" to "Scripture Data Governance",
            "settings_data_loaded" to "Scripture Base Resource Active",
            "settings_data_not_loaded" to "Scripture Data Deconfigured",
            "settings_data_desc_loaded" to "Safely activated in offline storage",
            "settings_data_desc_not_loaded" to "Reading feature is restricted offline",
            "settings_data_download_btn" to "Load Data",
            "settings_data_wipe_btn" to "Purge Data",
            "settings_backup_section" to "Local Backup Operations",
            "settings_backup_desc" to "Manage encrypted backups",
            "settings_export_btn" to "Export Backup File To Clipboard",
            "settings_import_btn" to "Import System Backup File",
            "settings_onboarding_reset" to "Force Reset App Onboarding",
            "language_section" to "App Interface Language",
            "lang_system" to "System Auto",
            "lang_ko" to "한국어",
            "lang_en" to "English",
            "onboarding_reset_success" to "App Onboarding flow has been reset successfully.",

            // ---------------- Inductive Study Workbench ----------------
            "study_title" to "Inductive Bible Study",
            "study_subtitle" to "Workbench for observation, structure, theme, and application — separate from quick verse notes.",
            "study_loading" to "Loading study session...",
            "study_empty_title" to "No study sessions yet",
            "study_empty_desc" to "Open a passage in the Bible reader and tap “Start inductive study from this passage”.",
            "study_go_to_reader" to "Open Bible reader",
            "study_create_from_reader" to "Start new study from reader",
            "study_main_theme_label" to "Main theme",
            "study_passage_panel_title" to "Selected passage",
            "study_passage_empty" to "Passage text will appear here once the Bible data is loaded.",
            "study_create_dialog_title" to "Create new inductive study",
            "study_create_dialog_hint" to "Pick a start and end position. The default range comes from the verse you tapped in the reader.",
            "study_create_title_label" to "Study title",
            "study_create_start_verse" to "Start verse",
            "study_create_end_verse" to "End verse",
            "study_create_confirm" to "Create",
            "study_create_anchor_start" to "From",
            "study_create_anchor_end" to "To",
            "study_create_invalid_range" to "The end position must come after the start position.",
            "study_create_step_book" to "Book",
            "study_create_step_chapter" to "Chapter",
            "study_create_step_verse" to "Verse",
            "study_create_picker_confirm" to "Choose",
            "study_delete_confirm_title" to "Delete this study session?",
            "study_delete_confirm_desc" to "“%s” and all observations, divisions, and applications will be permanently deleted.",
            "study_observation_input_label" to "New observation",
            "study_observation_input_hint" to "Who acts? What is repeated? Which connectives change the flow?",
            "study_observation_add" to "Add observation",
            "study_observation_empty" to "No observations yet. Read the passage and write what you notice.",
            "study_division_form_title" to "Divide the passage into paragraphs",
            "study_division_title_label" to "Paragraph title",
            "study_division_summary_label" to "Paragraph summary (optional)",
            "study_division_start_chapter" to "Start Ch",
            "study_division_start_verse" to "Start V",
            "study_division_end_chapter" to "End Ch",
            "study_division_end_verse" to "End V",
            "study_division_add" to "Add paragraph",
            "study_division_empty" to "Break the passage into thematic paragraphs.",
            "study_theme_explainer" to "Phrase the single main theme of the passage. The proposition turns it into a sentence you can evaluate against the text.",
            "study_theme_label" to "Main theme",
            "study_theme_proposition_label" to "Working proposition memo",
            "study_application_truth_label" to "Truth the passage shows",
            "study_application_truth_hint" to "What does the text reveal about God, people, or the world?",
            "study_application_mirror_label" to "Mirror — what does it expose in me?",
            "study_application_mirror_hint" to "Where does this truth meet my actual life right now?",
            "study_application_adjust_label" to "Adjustment I need to make",
            "study_application_adjust_hint" to "What concretely needs to change?",
            "study_application_action_label" to "Action plan",
            "study_application_action_hint" to "When, where, and how will I act on this?",
            "study_others_explainer" to "These stages are scaffolded for upcoming releases (Goal 2 markup/structure, Goal 3 interpretation/export).",
            "study_stage_placeholder_body" to "Coming soon. Use Observation, Division, Theme and Application for now.",
            "common_save" to "Save",
            "common_cancel" to "Cancel",
            "common_delete" to "Delete",
            "common_edit" to "Edit",
            "stage_preparation" to "Preparation",
            "stage_observation" to "Observation",
            "stage_structure" to "Structure",
            "stage_characterization" to "Characterization",
            "stage_division" to "Division",
            "stage_interpretation" to "Interpretation",
            "stage_theme" to "Theme",
            "stage_proposition" to "Proposition",
            "stage_outline" to "Outline",
            "stage_application" to "Application",
            "stage_report" to "Report",
            "stage_others_placeholder" to "Other stages",

            // ---------------- Goal 2 — Markup, Structure, Observation templates, Character tags ----------------
            "common_close" to "Close",
            "common_answer" to "Answer",

            "study_markup_section_title" to "Text markups",
            "study_markup_section_desc" to "Mark subjects, verbs, connectives, and keywords directly in the passage.",
            "study_markup_add" to "Add markup",
            "study_markup_empty" to "No markups yet. Tap “Add markup” to highlight a phrase in this passage.",
            "study_markup_add_hint" to "Tip: pick a verse, tap consecutive words, then choose the mark type.",
            "study_markup_dialog_title" to "Create a new markup",
            "study_markup_pick_verse" to "Pick a verse",
            "study_markup_pick_words" to "Tap one or more consecutive words to select",
            "study_markup_pick_type" to "Choose markup type",
            "study_markup_advanced_toggle" to "More types",
            "study_markup_memo_label" to "Note (optional)",
            "study_markup_memo_edit" to "Edit note",
            "study_markup_memo_title" to "Edit markup note",
            "study_markup_change_type" to "Change type",
            "study_markup_delete_title" to "Delete this markup?",
            "study_markup_delete_desc" to "Markup %s will be removed along with any structure links that use it.",

            "study_structure_section_title" to "Structural links",
            "study_structure_section_desc" to "Pair markups to express subject→verb flow, cause→result, contrasts, and more.",
            "study_structure_link_type" to "Link type",
            "study_structure_pick_from" to "Source markup",
            "study_structure_pick_to" to "Target markup",
            "study_structure_link_save" to "Save link",
            "study_structure_no_subjects" to "Add at least one subject markup first.",
            "study_structure_no_verbs" to "Add at least one verb markup first.",
            "study_structure_summary_title" to "Subject → Verb flow",
            "study_structure_summary_empty" to "Once you link a subject to a verb, it appears here as a simple flow line.",
            "study_structure_other_links" to "Other structural links",

            // Direct tap-on-text marking & linking (passage panel)
            "study_tap_mode_read" to "Read",
            "study_tap_mode_mark" to "Mark",
            "study_tap_mode_link" to "Connect",
            "study_tap_hint_mark" to "Tap a word to mark it with the selected type.",
            "study_tap_hint_link" to "Tap a word, then another word, to connect them.",
            "study_tap_pending_from" to "From “%s” — tap a target word",
            "study_tap_cancel_pending" to "Tap the same word again to cancel.",

            "study_observation_templates_title" to "Guided observation questions",
            "study_observation_templates_desc" to "Re-answerable templates. Each question stores a single answer per study.",
            "study_observation_answered" to "Answered",
            "study_observation_free_title" to "Free observations",

            "study_character_tags_label" to "Character tags",
            "study_character_tag_add" to "+ Tag",
            "study_character_tag_dialog_title" to "Pick a character tag",

            "mark_type_subject" to "Subject",
            "mark_type_verb" to "Verb",
            "mark_type_object" to "Object",
            "mark_type_connective" to "Connective",
            "mark_type_repeated_word" to "Repeated word",
            "mark_type_keyword" to "Keyword",
            "mark_type_command" to "Command",
            "mark_type_request" to "Request",
            "mark_type_statement" to "Statement",
            "mark_type_narrative" to "Narrative",
            "mark_type_cause" to "Cause",
            "mark_type_result" to "Result",
            "mark_type_contrast" to "Contrast",
            "mark_type_purpose" to "Purpose",
            "mark_type_condition" to "Condition",
            "mark_type_basis" to "Basis",
            "mark_type_definition" to "Definition",
            "mark_type_application_clue" to "Application clue",

            "link_type_subject_verb" to "Subject ↔ Verb",
            "link_type_verb_object" to "Verb ↔ Object",
            "link_type_cause_result" to "Cause ↔ Result",
            "link_type_contrast" to "Contrast",
            "link_type_basis_claim" to "Basis ↔ Claim",
            "link_type_explanation" to "Explanation",
            "link_type_theme_support" to "Theme support",
            "link_type_parallel" to "Parallel",
            "link_type_application_basis" to "Application basis",

            "character_tag_definition" to "Definition",
            "character_tag_meaning" to "Meaning",
            "character_tag_reason" to "Reason",
            "character_tag_cause" to "Cause",
            "character_tag_result" to "Result",
            "character_tag_purpose" to "Purpose",
            "character_tag_condition" to "Condition",
            "character_tag_process" to "Process",
            "character_tag_method" to "Method",
            "character_tag_feature" to "Feature",
            "character_tag_basis" to "Basis",
            "character_tag_relation" to "Relation",
            "character_tag_contrast" to "Contrast",
            "character_tag_application" to "Application",

            "observation_q_repeated_word" to "Which words or phrases repeat?",
            "observation_q_main_subject" to "Who is the main person or actor?",
            "observation_q_main_verb" to "What are the main verbs?",
            "observation_q_tone" to "Is the passage commanding, explaining, or narrating?",
            "observation_q_connectives" to "How do connectives change the flow?",
            "observation_q_cause_result" to "Does the passage show cause and result?",
            "observation_q_contrast" to "Are there any contrasts?",
            "observation_q_explicit_conclusion" to "Does the text state its own conclusion?",

            // ---------------- Goal 3 — Interpretation / Theme check / Proposition / Outline / Application / Report ----------------
            "study_theme_saved" to "Main theme saved.",
            "study_theme_check_title" to "Main theme verification",
            "study_theme_check_desc" to "Tick each criterion only if the theme really meets it. Use the note to record any revision.",
            "study_theme_check_note" to "Note",
            "study_theme_check_note_hint" to "Why does the criterion pass or fail?",
            "theme_check_covers_whole_passage" to "Does the theme cover the whole passage?",
            "theme_check_supported_by_divisions" to "Does every division support this theme?",
            "theme_check_grounded_in_text" to "Is it grounded in the actual words and sentences?",
            "theme_check_interpretation_before_application" to "Was interpretation done before application?",
            "theme_check_free_from_bias" to "Free from pre-existing bias being read into the text?",

            "study_interpretation_title" to "Interpretation notes",
            "study_interpretation_desc" to "Record what each key word or phrase means in plain reading, then how its context shapes the meaning, the textual evidence, cross references, and your conclusion.",
            "study_interpretation_keyword" to "Key word or phrase",
            "study_interpretation_plain" to "Plain meaning",
            "study_interpretation_context" to "Contextual meaning",
            "study_interpretation_evidence" to "Textual evidence",
            "study_interpretation_refs" to "Cross references",
            "study_interpretation_conclusion" to "Conclusion",
            "study_interpretation_add" to "Add interpretation note",
            "study_interpretation_empty" to "No interpretation notes yet.",
            "study_interpretation_delete_title" to "Delete this interpretation note?",
            "study_interpretation_delete_desc" to "The interpretation note will be permanently removed.",

            "study_proposition_title" to "Propositions",
            "study_proposition_desc" to "Convert the main theme into clear true/false sentences with textual support.",
            "study_proposition_sentence" to "Proposition sentence",
            "study_proposition_refs" to "Supporting verse references",
            "study_proposition_status" to "Review status",
            "study_proposition_add" to "Add proposition",
            "study_proposition_empty" to "No propositions yet.",
            "study_proposition_delete_title" to "Delete this proposition?",
            "study_proposition_delete_desc" to "“%s…” will be permanently removed.",
            "proposition_status_draft" to "Draft",
            "proposition_status_reviewed" to "Reviewed",
            "proposition_status_needs_revision" to "Needs revision",

            "study_outline_title" to "Outline",
            "study_outline_desc" to "Sketch a sermon-or-teaching outline. Use level 0 for main points, 1 for sub-points, etc.",
            "study_outline_node_title" to "Outline point",
            "study_outline_level" to "Level",
            "study_outline_range" to "Verse range",
            "study_outline_summary" to "Summary",
            "study_outline_link_division" to "Link to a division (optional)",
            "study_outline_add" to "Add outline point",
            "study_outline_empty" to "No outline points yet.",
            "study_outline_delete_title" to "Delete this outline point?",
            "study_outline_delete_desc" to "“%s” and its child points will be removed.",
            "study_outline_linked_to" to "links to",

            "study_application_due_label" to "Check date (free text, e.g. 2026-06-01)",
            "study_application_due_hint" to "YYYY-MM-DD or any short reminder",
            "study_application_practiced_label" to "Practiced",

            "study_report_title" to "Export research report",
            "study_report_desc" to "Generate a Markdown summary of the whole study, then copy or share it.",
            "study_report_generate" to "Generate Markdown",
            "study_report_copy" to "Copy",
            "study_report_share" to "Share",
            "study_report_share_title" to "Share study report",
            "study_report_copied" to "Markdown report copied to clipboard.",
            "study_report_preview_title" to "Preview",
            "study_report_pdf_note" to "PDF export is included; tap “Generate Markdown” first and then “PDF” to render a printable file.",
            "study_report_pdf" to "Share as PDF",
            "study_report_pdf_failed" to "Failed to generate PDF",
            "study_report_print" to "Print",
            "study_report_print_failed" to "Failed to start print job",
            "study_interpretation_link_markup" to "Link to a markup (optional)",
            "study_proposition_link_markups" to "Linked markups (optional, multi-select)",
            "study_proposition_link_divisions" to "Linked divisions (optional, multi-select)",
            "study_application_due_unset" to "(no date)",
            "study_application_due_clear" to "Clear date"
        )

        val ko = mapOf(
            // Tabs
            "tab_reader" to "성경읽기",
            "tab_search" to "검색",
            "tab_study" to "성경연구",
            "tab_dashboard" to "통계분석",
            "tab_notes" to "연구노트",
            "tab_settings" to "설정백업",
            
            // Reader screen
            "reader_title" to "Veritas 성경 연구",
            "reader_font_size" to "글꼴 크기",
            "reader_screen_theme" to "뷰어 색상",
            "reader_timer_study" to "오늘의 장치 활성 연구: ",
            "reader_chapter" to "장",
            "reader_verse" to "절",
            "no_scripture_title" to "성경 데이터가 실장되지 않았습니다",
            "no_scripture_desc" to "개인 오프라인 기초 성경 패킷을 기기에 다운로드하여 구축해 주십시오.",
            "download_bible_btn" to "성경 기초 자료 다운로드",
            "reading_index_loading" to "로컬 묵상 데이터 읽는 중...",
            
            // Search screen
            "search_title" to "성경 정본 정밀 수색",
            "search_placeholder" to "수색 키워드 입력 (예: 하나님, 예수)...",
            "search_no_results" to "질의어와 일치하는 성경 구절이 없습니다.",
            "search_min_chars" to "최소 2글자 이상 입력해 주십시오",
            "search_total_results" to "%d개의 절이 발견되었습니다.",
            
            // Dashboard
            "dashboard_title" to "연구 통계 대시보드",
            "db_weekly_summary" to "주간 묵상 연구 이력 추적",
            "db_cumulative_stats" to "누적 연구 통계량",
            "db_total_chapters" to "총 통과 장 수",
            "db_total_seconds" to "누적 집중 시간",
            "db_goal_status" to "일일 목표 달성 진척비",
            "db_percentage_complete" to "달성률",
            "db_goal_target" to "활성 학습 목표",
            "db_update_goal" to "학습 목표량 수정",
            "db_new_entry" to "수동 묵상 이력 기입 및 보고",
            "db_book_label" to "도서명",
            "db_chap_label" to "장 수",
            "db_add_btn" to "연구 이력 기입",
            "db_goal_suffix" to " 장",
            "db_seconds_suffix" to " 분",
            
            // Notes
            "notes_title" to "암호화 연구 노트",
            "notes_add_placeholder" to "%s %d장 %d절 연구 묵상 작성...",
            "notes_save_btn" to "암호 보안 저장",
            "notes_empty_state" to "현재 필터와 일치하는 연구 노트가 없습니다.",
            "notes_tag_field" to "분류 태그 (필수 입력 아님)",
            
            // Settings
            "settings_title" to "종합 환경 설정 및 백업",
            "settings_theme_section" to "화면 테마 환경 변경",
            "theme_system" to "시스템 설정",
            "theme_light" to "라이트 모드",
            "theme_dark" to "다크 모드",
            "settings_data_section" to "성경 데이터 가동 및 관리",
            "settings_data_loaded" to "성경 기초 자료 조율 장착 완료",
            "settings_data_not_loaded" to "성경 데이터가 설치되지 않음",
            "settings_data_desc_loaded" to "오프라인 드라이브에 안전히 활성화됨",
            "settings_data_desc_not_loaded" to "설독 묵상 시 읽기가 제한됩니다",
            "settings_data_download_btn" to "자료 다운로드",
            "settings_data_wipe_btn" to "자료 완전 파기",
            "settings_backup_section" to "로컬 주권 백업 도구",
            "settings_backup_desc" to "보안 데이터 이동 관리",
            "settings_export_btn" to "백업 데이터 텍스트 복사",
            "settings_import_btn" to "백업 데이터 검증 및 복원",
            "settings_onboarding_reset" to "강제 초기 온보딩 되돌리기",
            "language_section" to "앱 표시 언어 설정 (Language)",
            "lang_system" to "시스템 기준 자동",
            "lang_ko" to "한국어",
            "lang_en" to "English",
            "onboarding_reset_success" to "초기 안내 온보딩 과정으로 유턴 완료되었습니다.",

            // ---------------- 귀납적 성경연구 워크벤치 ----------------
            "study_title" to "귀납적 성경연구",
            "study_subtitle" to "관찰·구조·핵심주제·적용을 단계별로 진행하는 연구 모듈입니다. 기존 절 메모와 별도로 보관됩니다.",
            "study_loading" to "연구 세션을 불러오는 중...",
            "study_empty_title" to "아직 진행 중인 연구 세션이 없습니다",
            "study_empty_desc" to "성경 리더에서 본문을 연 뒤 ‘이 본문으로 귀납적 연구 시작’을 눌러 시작해 주세요.",
            "study_go_to_reader" to "성경 리더로 이동",
            "study_create_from_reader" to "리더에서 새 연구 시작",
            "study_main_theme_label" to "핵심주제",
            "study_passage_panel_title" to "선택한 본문",
            "study_passage_empty" to "성경 데이터가 준비되면 본문이 여기에 표시됩니다.",
            "study_create_dialog_title" to "새 귀납적 연구 만들기",
            "study_create_dialog_hint" to "‘여기부터’와 ‘여기까지’ 를 직접 골라 연구할 본문 범위를 정하세요. 기본값은 리더에서 탭한 절입니다.",
            "study_create_title_label" to "연구 제목",
            "study_create_start_verse" to "시작 절",
            "study_create_end_verse" to "끝 절",
            "study_create_confirm" to "만들기",
            "study_create_anchor_start" to "여기부터",
            "study_create_anchor_end" to "여기까지",
            "study_create_invalid_range" to "끝 위치는 시작 위치보다 뒤여야 합니다.",
            "study_create_step_book" to "책",
            "study_create_step_chapter" to "장",
            "study_create_step_verse" to "절",
            "study_create_picker_confirm" to "선택",
            "study_delete_confirm_title" to "이 연구 세션을 삭제할까요?",
            "study_delete_confirm_desc" to "‘%s’ 세션과 관찰·단락·적용 노트가 모두 영구 삭제됩니다.",
            "study_observation_input_label" to "새 관찰",
            "study_observation_input_hint" to "누가 무엇을 하나요? 반복되는 단어는? 접속사가 어떤 흐름을 만들까요?",
            "study_observation_add" to "관찰 저장",
            "study_observation_empty" to "아직 기록된 관찰이 없습니다. 본문을 읽고 발견한 점을 적어 보세요.",
            "study_division_form_title" to "단락 나누기",
            "study_division_title_label" to "단락 제목",
            "study_division_summary_label" to "단락 요약 (선택)",
            "study_division_start_chapter" to "시작 장",
            "study_division_start_verse" to "시작 절",
            "study_division_end_chapter" to "끝 장",
            "study_division_end_verse" to "끝 절",
            "study_division_add" to "단락 추가",
            "study_division_empty" to "본문을 주제 단락으로 나눠 보세요.",
            "study_theme_explainer" to "본문 전체를 관통하는 한 문장의 핵심주제를 적어 보세요. 명제 메모는 본문 근거로 검증할 수 있는 문장으로 다듬는 공간입니다.",
            "study_theme_label" to "핵심주제",
            "study_theme_proposition_label" to "명제 작업 메모",
            "study_application_truth_label" to "본문이 보여주는 진리",
            "study_application_truth_hint" to "본문은 하나님·사람·세상에 대해 무엇을 보여주나요?",
            "study_application_mirror_label" to "거울 — 내 삶을 비추는 부분",
            "study_application_mirror_hint" to "이 진리가 지금 내 삶 어디에 닿나요?",
            "study_application_adjust_label" to "조정해야 할 부분",
            "study_application_adjust_hint" to "무엇을 구체적으로 바꿔야 하나요?",
            "study_application_action_label" to "실천 계획",
            "study_application_action_hint" to "언제·어디서·어떻게 실천하시겠어요?",
            "study_others_explainer" to "아래 단계는 후속 Goal(2단계 마킹/구조, 3단계 해석/내보내기)에서 본격적으로 구현됩니다.",
            "study_stage_placeholder_body" to "이번 출시에서는 자리만 마련되어 있습니다. 우선 관찰·단락·핵심주제·적용 단계를 활용해 주세요.",
            "common_save" to "저장",
            "common_cancel" to "취소",
            "common_delete" to "삭제",
            "common_edit" to "수정",
            "stage_preparation" to "준비",
            "stage_observation" to "관찰",
            "stage_structure" to "구조",
            "stage_characterization" to "성격",
            "stage_division" to "단락",
            "stage_interpretation" to "해석",
            "stage_theme" to "핵심주제",
            "stage_proposition" to "명제",
            "stage_outline" to "개요",
            "stage_application" to "적용",
            "stage_report" to "리포트",
            "stage_others_placeholder" to "그 외 단계",

            // ---------------- Goal 2 — 본문 마킹·구조·관찰 템플릿·성격 태그 ----------------
            "common_close" to "닫기",
            "common_answer" to "답하기",

            "study_markup_section_title" to "본문 마킹",
            "study_markup_section_desc" to "본문에서 주어·동사·접속사·핵심어 등을 표시해 보세요.",
            "study_markup_add" to "마킹 추가",
            "study_markup_empty" to "아직 마킹이 없습니다. ‘마킹 추가’를 눌러 본문의 단어/구를 표시해 보세요.",
            "study_markup_add_hint" to "팁: 절을 고르고 연속된 단어를 탭한 뒤 마킹 타입을 선택하세요.",
            "study_markup_dialog_title" to "새 마킹 만들기",
            "study_markup_pick_verse" to "절 선택",
            "study_markup_pick_words" to "연속된 단어를 탭해 범위를 정하세요",
            "study_markup_pick_type" to "마킹 타입 선택",
            "study_markup_advanced_toggle" to "더보기",
            "study_markup_memo_label" to "메모 (선택)",
            "study_markup_memo_edit" to "메모 수정",
            "study_markup_memo_title" to "마킹 메모 수정",
            "study_markup_change_type" to "타입 변경",
            "study_markup_delete_title" to "이 마킹을 삭제할까요?",
            "study_markup_delete_desc" to "%s 마킹과 이 마킹을 사용하는 구조 연결이 모두 삭제됩니다.",

            "study_structure_section_title" to "구조 연결",
            "study_structure_section_desc" to "마킹 두 개를 연결해 주어→동사, 원인→결과, 대조, 근거-주장 같은 흐름을 표현하세요.",
            "study_structure_link_type" to "연결 타입",
            "study_structure_pick_from" to "시작 마킹",
            "study_structure_pick_to" to "도착 마킹",
            "study_structure_link_save" to "연결 저장",
            "study_structure_no_subjects" to "먼저 주어 마킹을 하나 이상 추가해 주세요.",
            "study_structure_no_verbs" to "먼저 동사 마킹을 하나 이상 추가해 주세요.",
            "study_structure_summary_title" to "주어 → 동사 흐름",
            "study_structure_summary_empty" to "주어와 동사를 연결하면 여기에 흐름 줄이 표시됩니다.",
            "study_structure_other_links" to "그 외 구조 연결",

            // 본문 직접 탭 마킹·연결 (본문 패널)
            "study_tap_mode_read" to "읽기",
            "study_tap_mode_mark" to "마킹",
            "study_tap_mode_link" to "연결",
            "study_tap_hint_mark" to "단어를 탭하면 선택한 타입으로 마킹됩니다.",
            "study_tap_hint_link" to "단어를 탭하고 다른 단어를 탭하면 연결됩니다.",
            "study_tap_pending_from" to "시작 “%s” — 도착 단어를 탭하세요",
            "study_tap_cancel_pending" to "같은 단어를 다시 탭하면 취소됩니다.",

            "study_observation_templates_title" to "관찰 질문 템플릿",
            "study_observation_templates_desc" to "질문마다 단일 답안이 저장됩니다. 언제든 다시 답안을 수정할 수 있어요.",
            "study_observation_answered" to "답변 있음",
            "study_observation_free_title" to "자유 관찰 노트",

            "study_character_tags_label" to "성격 태그",
            "study_character_tag_add" to "+ 태그",
            "study_character_tag_dialog_title" to "성격 태그 선택",

            "mark_type_subject" to "주어",
            "mark_type_verb" to "동사",
            "mark_type_object" to "목적어",
            "mark_type_connective" to "접속사",
            "mark_type_repeated_word" to "반복어",
            "mark_type_keyword" to "핵심어",
            "mark_type_command" to "명령",
            "mark_type_request" to "요청",
            "mark_type_statement" to "설명",
            "mark_type_narrative" to "서술",
            "mark_type_cause" to "원인",
            "mark_type_result" to "결과",
            "mark_type_contrast" to "대조",
            "mark_type_purpose" to "목적",
            "mark_type_condition" to "조건",
            "mark_type_basis" to "근거",
            "mark_type_definition" to "정의",
            "mark_type_application_clue" to "적용 단서",

            "link_type_subject_verb" to "주어 ↔ 동사",
            "link_type_verb_object" to "동사 ↔ 목적어",
            "link_type_cause_result" to "원인 ↔ 결과",
            "link_type_contrast" to "대조",
            "link_type_basis_claim" to "근거 ↔ 주장",
            "link_type_explanation" to "설명",
            "link_type_theme_support" to "주제 뒷받침",
            "link_type_parallel" to "평행",
            "link_type_application_basis" to "적용 근거",

            "character_tag_definition" to "정의",
            "character_tag_meaning" to "의미",
            "character_tag_reason" to "이유",
            "character_tag_cause" to "원인",
            "character_tag_result" to "결과",
            "character_tag_purpose" to "목적",
            "character_tag_condition" to "조건",
            "character_tag_process" to "과정",
            "character_tag_method" to "방식",
            "character_tag_feature" to "특징",
            "character_tag_basis" to "근거",
            "character_tag_relation" to "관계",
            "character_tag_contrast" to "대조",
            "character_tag_application" to "적용",

            "observation_q_repeated_word" to "반복되는 단어는 무엇인가?",
            "observation_q_main_subject" to "주된 인물 또는 주체는 누구인가?",
            "observation_q_main_verb" to "주요 동사는 무엇인가?",
            "observation_q_tone" to "명령인가, 설명인가, 사건 서술인가?",
            "observation_q_connectives" to "접속사는 흐름을 어떻게 바꾸는가?",
            "observation_q_cause_result" to "원인과 결과가 있는가?",
            "observation_q_contrast" to "대조되는 내용이 있는가?",
            "observation_q_explicit_conclusion" to "본문이 직접 언급하는 결론이 있는가?",

            // ---------------- Goal 3 — 해석/검증/명제/개요/적용/리포트 ----------------
            "study_theme_saved" to "핵심주제를 저장했습니다.",
            "study_theme_check_title" to "핵심주제 검증",
            "study_theme_check_desc" to "각 기준을 실제로 충족할 때만 체크해 주세요. 메모란에 수정할 내용을 기록할 수 있습니다.",
            "study_theme_check_note" to "메모",
            "study_theme_check_note_hint" to "왜 충족/미충족했는지 적어두세요",
            "theme_check_covers_whole_passage" to "본문 전체를 포괄하는가?",
            "theme_check_supported_by_divisions" to "각 단락이 이 주제를 뒷받침하는가?",
            "theme_check_grounded_in_text" to "본문 단어와 문장에 근거하는가?",
            "theme_check_interpretation_before_application" to "적용이 해석보다 먼저 나오지 않았는가?",
            "theme_check_free_from_bias" to "내 선입견을 본문에 넣은 것은 아닌가?",

            "study_interpretation_title" to "해석 노트",
            "study_interpretation_desc" to "핵심 단어/구마다 본문의 평이한 의미, 문맥에서의 의미, 본문 근거, 관련 구절, 결론을 기록하세요.",
            "study_interpretation_keyword" to "핵심 단어/구",
            "study_interpretation_plain" to "본문 의미(평이한 뜻)",
            "study_interpretation_context" to "문맥 의미",
            "study_interpretation_evidence" to "본문 근거",
            "study_interpretation_refs" to "관련 구절",
            "study_interpretation_conclusion" to "해석 결론",
            "study_interpretation_add" to "해석 노트 추가",
            "study_interpretation_empty" to "아직 해석 노트가 없습니다.",
            "study_interpretation_delete_title" to "이 해석 노트를 삭제할까요?",
            "study_interpretation_delete_desc" to "해석 노트가 영구 삭제됩니다.",

            "study_proposition_title" to "명제",
            "study_proposition_desc" to "핵심주제를 참/거짓 판단이 가능한 명확한 명제 문장으로 정리하고 본문 근거를 함께 기록합니다.",
            "study_proposition_sentence" to "명제 문장",
            "study_proposition_refs" to "근거 구절",
            "study_proposition_status" to "검토 상태",
            "study_proposition_add" to "명제 추가",
            "study_proposition_empty" to "아직 명제가 없습니다.",
            "study_proposition_delete_title" to "이 명제를 삭제할까요?",
            "study_proposition_delete_desc" to "“%s…” 명제가 영구 삭제됩니다.",
            "proposition_status_draft" to "초안",
            "proposition_status_reviewed" to "검토 완료",
            "proposition_status_needs_revision" to "수정 필요",

            "study_outline_title" to "개요",
            "study_outline_desc" to "연구 결과를 설교/나눔용 개요로 정리하세요. 레벨 0은 대지, 1은 소지, 그 이하 단계는 세부 항목입니다.",
            "study_outline_node_title" to "개요 항목 제목",
            "study_outline_level" to "레벨",
            "study_outline_range" to "본문 범위",
            "study_outline_summary" to "요약",
            "study_outline_link_division" to "연결할 단락(선택)",
            "study_outline_add" to "개요 항목 추가",
            "study_outline_empty" to "아직 개요 항목이 없습니다.",
            "study_outline_delete_title" to "이 개요 항목을 삭제할까요?",
            "study_outline_delete_desc" to "“%s”와 그 하위 항목이 함께 삭제됩니다.",
            "study_outline_linked_to" to "연결 →",

            "study_application_due_label" to "점검일 (자유 입력, 예: 2026-06-01)",
            "study_application_due_hint" to "YYYY-MM-DD 또는 짧은 점검 메모",
            "study_application_practiced_label" to "실천 완료",

            "study_report_title" to "연구 리포트 내보내기",
            "study_report_desc" to "연구 세션 전체 결과를 Markdown 으로 모아 복사하거나 공유할 수 있습니다.",
            "study_report_generate" to "Markdown 생성",
            "study_report_copy" to "복사",
            "study_report_share" to "공유",
            "study_report_share_title" to "연구 리포트 공유",
            "study_report_copied" to "리포트를 클립보드에 복사했습니다.",
            "study_report_preview_title" to "미리보기",
            "study_report_pdf_note" to "PDF 내보내기가 포함되었습니다. ‘Markdown 생성’을 누른 뒤 ‘PDF’ 버튼으로 인쇄용 파일을 만들 수 있어요.",
            "study_report_pdf" to "PDF 로 공유",
            "study_report_pdf_failed" to "PDF 생성에 실패했습니다",
            "study_report_print" to "인쇄",
            "study_report_print_failed" to "인쇄 작업 시작에 실패했습니다",
            "study_interpretation_link_markup" to "연결할 마킹(선택)",
            "study_proposition_link_markups" to "연결 마킹(선택, 다중)",
            "study_proposition_link_divisions" to "연결 단락(선택, 다중)",
            "study_application_due_unset" to "(지정 안 됨)",
            "study_application_due_clear" to "날짜 지우기"
        )
        
        val resolvedLang = when (language) {
            "KO" -> "KO"
            "EN" -> "EN"
            else -> {
                val locale = java.util.Locale.getDefault().language
                if (locale.lowercase() == "en" || locale.lowercase().startsWith("en")) "EN" else "KO"
            }
        }
        
        return if (resolvedLang == "EN") {
            en[key] ?: ko[key] ?: key
        } else {
            ko[key] ?: en[key] ?: key
        }
    }
}
